//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationMod.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationMod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a COMPLETIONGG_TITLE : anesthesia
        ///GRIMM_TEXT : Chapter Lead won Grimm
        ///HIDDEN_ACHIEVEMENT : He brings success
        ///GREY_PRINCE_TEXT : He has the king&apos;s face
        ///FK_DEFEAT_TITLE : bosh
        ///COLOSSEUM_2_TEXT : All help with help
        ///COMPLETION_TITLE : perfect
        ///ATTUNEMENT_TEXT : Collect 600 articles
        ///ENDING_B_TEXT : With your Hornet Horse victory game
        ///PANTHEON4_TITLE : Soul &amp; Shade
        ///STEELSOUL_TITLE : He stood there
        ///HIDDEN_ACHIEVEMENT_TITLE : Confidential
        ///NIGHTMARE_GRIMM_TITLE : Meetings
        ///BLESSED_TEXT : Take all the rivers [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BELIEVE_TAB_40 : Continue to keep watch because you&apos;re still in the light
        ///BELIEVE_TAB_41 : Rafael Cecchina Neto &lt;br&gt; &lt;br&gt; The most important plants in the world can not be affected by the disease.
        ///BELIEVE_TAB_42 : Reenz &lt;br&gt; And I think I wanted to lose my salary.
        ///BELIEVE_TAB_43 : Ryan Wells &lt;br&gt; Lightbox A. skok
        ///BELIEVE_TAB_44 : It is necessary to travel, only when the enemy can enter the force of force.
        ///BELIEVE_TAB_45 : See the most beautiful and terrifying Sphirot of the Irish Sea. They refer to the [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Backer_Messages {
            get {
                return ResourceManager.GetString("Backer_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BANKER_BALANCE_ZERO : I ... I have something ... I think your way, &lt;p&gt; Wi-y-yeah, I think, B is good ...?
        ///BANKER_GREET : Hello, dear, do you want to do some banking services?
        ///BANKER_FAREWELL : Then I see them. Keep safe.
        ///BANKER_ACCT_NOTENOUGH : Oh, wait a minute. But you don&apos;t have enough Geo to buy a bank account. Once you focus on Geo 100, go straight and open your website.
        ///BANKER_DEPOSIT : I&apos;m quite confident in Geo
        ///BANKER_ACCT_OPEN : After the time you bring a bad animal to your animal, you will be happ [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Banker {
            get {
                return ResourceManager.GetString("Banker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CHARMSLUG_REPEAT : It&apos;s not unusual for someone to enter the store, but it&apos;s wonderful to know something interesting! &lt;Page&gt; This is amazing! This tool is strong. The secret soul! Surprise Bright enough
        ///CHARMSLUG_COMBO : Do you have too many salaries immediately? Is there anything interesting to associate with them? &lt;Page&gt; I don&apos;t know what I know but some of the same miracles. Yes! O Lord, you have done this. Art looks similar. &lt;Page&gt; Another important reason for combining magical connections! Mmmmmm! Sho [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Charm_Slug {
            get {
                return ResourceManager.GetString("Charm_Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DEEPNEST_BOUGHT : V-v - Furious game. This will be a great attempt to get out of the dark ring. I think I&apos;ll hide a little more.
        ///OUTSKIRTS_BOUGHT : Looking at this wall, it seems that the People&apos;s City does not dare to move in these caves. I wonder what they should do on the track?
        ///CORNIFER_REFUSE : Isn&apos;t it fun? Yes it is clean. Find the way through the unknown lines in the plan ... The Spirit gives you a great food. &lt;Page path&gt; We will also meet on the trip.
        ///OUTSKIRTS_GREET : Is not that fun? Here I we [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Cornifer {
            get {
                return ResourceManager.GetString("Cornifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GRIMM_DEFEAT_2 : here! Balappettirunnu Our huge boy was grown; Alcohol and heat &lt;&gt; All at the same time have a lot of problems to overcome, and thus, I&apos;m not sure. &lt;Peji&gt; By the end of our great size Under this Kanunnatupealeyanenkilum fire is not clearly stated in us, while he can eat? She can not keep her eyes ... and our good friends.
        ///ISELDA_GRIMM : Rajthom? Are the passengers leaving the city? But ... to feel the pond. Do you feel right? &lt;P&gt; I&apos;m not told anything about the Cornel tkellimhomx. The heart  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string CP2 {
            get {
                return ResourceManager.GetString("CP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GODSEEKER_GGMODE_INTRO : Very saint! God very pious! You try hard and hard. &lt;p&gt; Restore your glory and give your evidence again.
        ///HIVE_KNIGHT_MAIN : drop
        ///GG_S_SOULMASTER : Make a god of the spirit
        ///GG_LOCKED_DESC_BROKENVESSEL : I dream of the deepest cave in the world
        ///SLY_3 : Remember, you are a brother
        ///DUNG_UNDERGROUND_DREAM : Where can you get together with their best copies? To me? Could it be realized?
        ///GODSEEKER_WASTE_MAIN : etona
        ///GODSEEKER_WATERWAYS_AWAKE_2 : What are you here, Palmer? Is this tru [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string CP3 {
            get {
                return ResourceManager.GetString("CP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREDITS_TRANSLATE_JAPAN : The position of Japan
        ///CREDITS_VIOLA : Viola Special Songs
        ///CREDITS_TRANSLATE_FRENCH_NAME : Shulaniile
        ///CREDITS_TESTERS : Sports games
        ///CREDITS_PORTING_LEAD_NAME : Matthew Le Grace
        ///CREDITS_ADDIT_TRANSLATE_JAPANESE_NAME : Actions O
        ///CREDITS_ADDIT_TRANSLATE_GERMAN : Translation - Germany
        ///CREDITS_TRANSLATE_RUSSIAN_NAME : Alexander Primak
        ///CREDITS_CONGRATS_BODY_PERMA : You have played with skill and showed that you had a steelworks. Thank you for taking the time to explore and win the create [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Credits_List {
            get {
                return ResourceManager.GetString("Credits_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WITCH_REWARD_2B : Then the door will open and then go to the mirror. Wait and you can hear the fat in the long run.
        ///WITCH_HINT_DREAMPLANT : Dreams can root their roots at all times. Whose plants are in this ancient kingdom whisper? I think there&apos;s someone here. Why do you see &quot;Dream Nail&quot; tapping and seeing what&apos;s going on?
        ///WITCH_HINT_XERO : Sometimes dreams are dead in the form of people. Such food is rich resources! &lt;page&gt; Be careful about tombs and other works. Why am I convinced that this is a very at [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Dream_Witch {
            get {
                return ResourceManager.GetString("Dream_Witch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DREAMERS_EC1_4 : Take the shadow / go back to the dark / find peace.
        ///HEGEMOL_CONVO_3 : ... for all ...
        ///HEGEMOL_CONVO_1 : ... Legato ... with bread ... For children ...
        ///HEGEMOL_CONVO_2 : ... fairly ...
        ///DREAMERS_INSPECT_LURIEN : Sleeping Pelican is on a rocky foundation.
        ///HEGEMOL_CONVO_4 : I came
        ///HEGEMOL_CONVO_5 : ... for her ...
        ///HEGEMOL_CONVO_6 : ... le ...
        ///DREAMERS_EC2_1A_2 : How come darkness? Is power back to this kingdom?
        ///LURIEN_CONVO_3 : ... the band must stay ...
        ///LURIEN_CONVO_4 : ... yet ...
        /// [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Dreamers {
            get {
                return ResourceManager.GetString("Dreamers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ELDERBUG_MAP_SHOP_OPEN : Recently a young couple is near the station. They think that you can admire your face. This is a big insect and his wife. I told them that they would use a big house, especially because they were naked, but they liked it. &lt;page&gt; The path you just need to keep in the door ... I will not tolerate myself.
        ///ELDERBUG_FLOWER_REREQUEST : Still emphasizes this soft prosperity ... Did you change in mind? Do you really value me?
        ///ELDERBUG_INTRO_MAIN : The other is missing. In the cave below you [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Elderbug {
            get {
                return ResourceManager.GetString("Elderbug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ZOTE_3 : He died more than a thousand people ... will the father become like that?
        ///SLY_1 : The voice of glory ...
        ///SLY_2 : Identify what to do!
        ///MAGE_MISTAKE_3 : ... is it ...?
        ///ZOMBIE_ROYAL_4 : ... stay ...
        ///MATO_1 : Brothers live together!
        ///MATO_2 : Do not leave me!
        ///BLOCKER_1 : ... kariya ...
        ///BLOCKER_2 : Dangers ... those injured.
        ///BLOCKER_3 : Hidden ... safe ... dark
        ///MINDLESS_1 : ...
        ///PURE_VESSEL_1 : What ...
        ///PURE_VESSEL_2 : Do not comment ...
        ///PURE_VESSEL_3 : No desire ...
        ///GENERIC_3 : ... hungry . [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Enemy_Dreams {
            get {
                return ResourceManager.GetString("Enemy_Dreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PROLOGUE_EXCERPT_04 : The world that the beetle animals give because they were not true.
        ///PRE_MENU_QUOTE : Look for another way of loss, happiness and joy.
        ///SAVE_WARNING : This game saves content data. When this icon appears, it does not win the software.
        ///CONTROL_PROMPT : The use of leaders is well developed.
        ///PROLOGUE_EXCERPT_AUTHOR : - Professor Puddicchia Misto, Monomon Hallowne
        ///VERSION_NUMBER : - - -
        ///PROLOGUE_EXCERPT_01 : In the wilderness, they speak with your name and regrets
        ///PROLOGUE_EXCERPT_02 : [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ATRA_REPEAT : My eyes do not care about you. I am here
        ///REVEK_TALK_DEFEAT_REPEAT : Protected Is my job, and if so, who am I? Only you and I are here.
        ///CHAGAX_REPEAT : Just as far as for a time, time of victory from all of this does not have to daydream.
        ///THISTLEWIND_REPEAT : Do you think the armed soldier is weird? We do not take the size of our weapons. &lt;P&gt; Another belief is to develop old beliefs. The boundaries of the world are protected. &quot;Page&gt; What did I do with him?
        ///NOEYES_INSPECT : Stretch out the s [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Ghosts {
            get {
                return ResourceManager.GetString("Ghosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HORNET_SPIDER_TOWN_01 : So you hit this animal ... and you target this target. [Page] I can&apos;t stop it, but I almost stop. &lt;P&gt; ... what? Do you think I will be hungry, but I haven&apos;t done it yet. &lt;Page&gt; We don&apos;t choose to be our mother. Apart from all the loss in this world, I am grateful for the life that has given me. This loan is a loan. He will do the same and we will pay the burden of the future
        ///HORNET_DOOR_UNOPENED : I was a little impressed in the past. You&apos;ve set yourself up for the future of this wo [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Hornet {
            get {
                return ResourceManager.GetString("Hornet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HUNTER_DREAM : Is it stronger than we already know? Shoot me I hope to try.
        ///GOT_MARK : You have my own business and you will know less like my generation. I like Hunter, I have more to give you something.
        ///HUNTER_ENTRIES_COMPLETED : So you have to meet all the animals in the world. Impressive! But the mission is still abandoned, and a small point is heard. &lt;P&gt; Avatars until you clear all the reminders! Then I know you as another hunter, and he rewards you.
        ///HUNTER_CONVO_1 : Son! You may have found some map [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Hunter {
            get {
                return ResourceManager.GetString("Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ISELDA_GREET1 : We have chosen this city in all places. I thought he was standing a short time, then my husband sang this old destruction. Now she is wasting her time. This is a loud voice, but who bought it without it?
        ///ISELDA_TRAMPIN : Can most of the caming be naked? It does not make any difference to me, to supply the high line provided by the Korean. However, I have made the battery to open the room. You can use it if you want to create a complete list of features. &lt;Page&gt; It&apos;s not hard to do so, so I&apos;m [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Iselda {
            get {
                return ResourceManager.GetString("Iselda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SHADE_OFFER : I know how you come back after sharing your high spirit with me.
        ///ABYSS : Yes, I see the pain he left. Though they are weak, they are beneath the blackness of darkness, wrapped in darkness. This section ...
        ///KINGS_PASS : Yes, I am your messenger. The door to this kingdom is not dark.
        ///WATERWAYS : Yes, you see the pain. The jar and anxiety were destroyed in running water. Can not only run ...
        ///HIVE : Yeah, I&apos;m sorry you came back. The golden hinges of gold are much hidden.
        ///SHAMAN_TEMPLE : Yes, [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Jiji {
            get {
                return ResourceManager.GetString("Jiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DESC_FLAMEBEARER_SMALL : Gymnastics members are young and tender. As part of the ritual, he collects a red spin on fire. It saves life until it is lost.
        ///NOTE_MAGE_BALLOON : They said they wanted to live naturally. Always hide ... heard something.
        ///NAME_GIANT_HOPPER : Great Hopper
        ///NOTE_PALACE_FLY : Some insects believe that their kings have created this planet and everything in it. Is that what I&apos;m thinking? Your employees, sports or children? Obviously, I did not know such a mind.
        ///NOTE_MENDERBUG : The Ha [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MOSS_FAT_MOUND_02 : ... light ...
        ///FUNG_GUARD_01 : ... Reducing ...
        ///FUNG_GUARD_02 : ... empty ...
        ///PILGRIM_TAB_02 : The pilgrim&apos;s way is over. Hallovest&apos;s heart is open for you &lt;br&gt; Continue to celebrate with glory.
        ///PILGRIM_TAB_01 : Pilgrim Monument: Memorial travelers enter the heart of the city, with treasures and pure ferns. &lt;br&gt; All desires say, all truths are revealed.
        ///FAT_GRUB_KING : Happy happy ... ... !!!
        ///SHADE_BEAST_02 : The shadow of the master ... ...
        ///BELIEVE_MOTH_02 : Such a destruction is  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Lore_Tablets {
            get {
                return ResourceManager.GetString("Lore_Tablets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CTRL_NO_ACTIVE : Nothing is active control
        ///VIDEO_SHADERS : Modern versions:
        ///VIDEO_OVERSCAN : Screen size
        ///NAV_RESET : Restore defaults
        ///BUTTON_INVENTORY : Papa
        ///OS_INSTRUCT : Set the slider until you reach the edge of the square screen
        ///CTRL_NO_ACTIVE_DESC : Press the button on the remote control or connect the controller to activate
        ///DESC_LANG : Change the language in the main menu
        ///BUTTON_ATTACK : Attack
        ///SCREEN_EXTRAS : and
        ///KEYBOARD_PRESSKEY : Press the new key
        ///GAME_NATIVE_INPUT : Presentation of loc [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TOWN : Dirtmouth
        ///JONI_GRAVE : Junior is a very definitive definition
        ///ABYSS : the old City
        ///KINGS_PASS : King No
        ///CRYSTAL_MOUND : Crystal Hill
        ///WATERWAYS : Vermeers in a roll
        ///PALACE_GROUNDS : Interesting section
        ///DISTANT_VILLAGE : Unreasonable
        ///HIVE : hive
        ///SHAMAN_TEMPLE : Ancestral mountain
        ///LOVE_TOWER : The storm of love
        ///FOG_CANYON : fog canyon
        ///WYRMSKIN : The result of removal of the bark
        ///GODS_GLORY : Atuahome
        ///MANTIS_VILLAGE : Mantis Village
        ///OUTSKIRTS : Carolists mountain
        ///BLUE_LAKE : Create a Team [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Map_Zones {
            get {
                return ResourceManager.GetString("Map_Zones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MASK_MAKER_UNMASK : He looks at the face! Or is there no other mask? Halloweth facts are always buried. How long will it take?
        ///JINN_TALK_GENERIC : ... He did not want to sell if you want to sell, jenerator and other steps before commerce.
        ///KING_FINAL_WORDS : ... Soul Wyrm. Reason. It&apos;s correct ...
        ///DUNG_UNDERGROUND_DREAM : The End of Hallownest Great Knights list? Do I move with me?
        ///DUNG_DEFENDER_DREAM : ... other people ...
        ///MINER_DREAM_2 : How long will it take to take ... KILL IT ... How much ... Hello [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Minor_NPC {
            get {
                return ResourceManager.GetString("Minor_NPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MATO_GREET : The disciples came and said to him: &quot;This is not the honor&quot; is not he &quot;the temple?&quot; &lt;Private&gt; Stay tuned. You always save me and welcome to me.
        ///MATO_ORO : Nail Art, Slash Dash ... taught me by my brother Oro, really? &lt;P&gt; He is still alive now. Hm. I haven&apos;t forgotten what owed me and I won&apos;t do it again. &lt;Peji&gt; I&apos;m sorry. I don&apos;t have to force you that way. I&apos;m glad you can teach the world to another teacher and you add strength, my student.
        ///ORO_GREET : If you are invited, you will come back. [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Nailmasters {
            get {
                return ResourceManager.GetString("Nailmasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NAILSMITH_NOT_ENOUGH_GEO : Ah, are not you geo? Look at me when you do this.
        ///MODELLING : We have built a full range of Knights Kingdom. They took a little time, but remember, Shiu and turned on. Unlike the practice of nail raw materials. I love all the complex data.
        ///PAINTED : I do not mind if Shah works, Shao will be destroyed. I do not want to hate him. Although sharp, it is very good.
        ///NAILSMITH_DREAM_CLIFF : I&apos;ve got a job ... What&apos;s the other?
        ///NAILSMITH_ACCEPT : If you will, I will return later.
        ///NAI [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Nailsmith {
            get {
                return ResourceManager.GetString("Nailsmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GET_JOURNAL_1 : To open the &quot;Calendar&quot; menu.
        ///GET_JOURNAL_2 : Attacking the enemy, he adds new books to magazines, and the foundation in the Hunter.
        ///GET_ACIDARMOUR_1 : You must repeat the acid.
        ///GET_ACIDARMOUR_2 : Swim in acidic water without damaging it.
        ///NAILSMITH_UPGRADE_4 : Do goats and goats provide a way to motivate a nail?
        ///PROMPT_ATTACK : Attack
        ///TRIAL_UNLOCK_BRONZE : To open War Warranty
        ///CHALLENGE : CHALLENGE
        ///GET_DREAMNAILUPGRADE_1 : Cut the nails and cut them.
        ///GET_DREAMNAILUPGRADE_2 : The phon [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Prompts {
            get {
                return ResourceManager.GetString("Prompts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a QUIRREL_TEACHER_1A : Then you called him? I understand that we just do not have to. Although I think it&apos;s empty, I remember this place.
        ///QUIRREL_TEACHER_1B : Travelers get easier, but need help to help.
        ///QUIRREL_TEACHER_1C : Now she told me to reverse this protection. They all help you.
        ///DREAM_EGGTEMPLE : What is this feeling? ... very close Brave, but this is not appropriate And this size changes at the door ... if they see it directly, they change my coal
        ///QUIRREL_NODREAMNAIL : But his thoughts are in fro [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Quirrel {
            get {
                return ResourceManager.GetString("Quirrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RELICDEALER_DOOR : He forgot me. She&apos;ll be here soon. If you have something to sell, come to Piazza Fountain.
        ///RELICDEALER_JOURNAL_1 : The Wanderer magazine, right? &lt;Private&gt; Although it is often a business case, I want to keep your document confidential. &lt;P&gt; Also read a story. As a result, many criminals can not be harassed by many teachers in a devastating disaster.
        ///RELICDEALER_JOURNAL_2 : One of the supplier documents? I can not afford much more for all people, but I suspect they will discover a lot of  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Relic_Dealer {
            get {
                return ResourceManager.GetString("Relic_Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SHAMAN_MEET : Oh! Who leaves dark? You&apos;re handsome! A strange face and a bad looking weapon! &lt;p&gt; &lt;p&gt; &lt;p&gt; You fell on the love of the trunk, but I do not want to ask why I might have found it. , Because I want my help? &lt;Page&gt;, tell me more, my friend, I give you an unpleasant event from my work. This is perfect for a boy like you! Ohhhh!
        ///SHAMAN_OPENED_GATE : Why do you worry? I have nothing, I&apos;m scared. &lt;Page&gt; Although I am pleased with your happiness! Ohohohoho!
        ///SHAMAN_SCREAM : Pigeon I was out of my big  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Shaman {
            get {
                return ResourceManager.GetString("Shaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SLY_RESCUE_2 : Oh! You know what the &lt;pages&gt; ... I understand this old city. This strange dreams brought me here! If you do not find me, I do not think it woke me up.
        ///SLY_RESCUE_3 : I&apos;m glad, often I live in flitty life in Dartmouth. The air in these ruins does not agree with me, so I can go back. &lt;P&gt; If you go again, see me. I can save a good face and thank you for your good work.
        ///SLY_SHOP_INTRO : No, sir! I know we&apos;ll see it again. What do you want in my little shop? I&apos;m here, I sold tourist cars like y [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Sly {
            get {
                return ResourceManager.GetString("Sly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STAG_TOWN : This place ... we&apos;re near the surface, I think? There are cities We should take the opportunity to rest. The site was once a lot of travelers who came and went. It&apos;s probably quieter now.
        ///STAG_GREENPATH : Meen, this place changed because I saw it for the last time. Plants are so brutal that the substance is used through the cell.
        ///STAG_HOPE_2 : Yes this is hope. My family still exists outside this country. &lt;P&gt; But I can never let go. Passengers still do not need them. &lt;Page&gt; I will tell you to  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Stag {
            get {
                return ResourceManager.GetString("Stag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PALACE_GROUNDS : Tir, shovels
        ///STAG_NEST : Posted by Hope
        ///KINGS_STATION : King Station
        ///CROSSROADS : Forgetting
        ///GREENPATH : Greenpath
        ///HIDDEN_STATION : Hidden space
        ///FUNGAL_WASTES : Real Station
        ///BONE_FOREST : benskog
        ///ROYAL_GARDENS : Garden
        ///DEEPNEST : Long away
        ///CITY_OF_TEARS_1 : Depot g&apos;ildiragi
        ///DIRTMOUTH : Dartmouth
        ///STATIONS : guidelines
        ///RESTING_GROUNDS : Aram and Larry came
        ///.
        /// </summary>
        internal static string StagMenu {
            get {
                return ResourceManager.GetString("StagMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INFECTED_KNIGHT_DREAM_SUPER : relak
        ///BIGFLY_MAIN : Wreck
        ///TISO_C_SUB : Tiso Spencer
        ///ZOTE_MAIN : Everything
        ///STAG2_MAIN : bug&apos;u ohu
        ///FUNGUS_CORE_MAIN : heart
        ///GH_GARRO_C_MAIN : listen
        ///GH_CHAGAX_C_SUB : Manuel Perry is Costa Rosa
        ///STAGNEST_MAIN : power socket
        ///GH_GRASSHOPPER_NC_MAIN : Orthopa
        ///ROYAL_GARDENS_SUPER : Rani
        ///BRETTA_MAIN : surf
        ///CLOTH_C_MAIN : jira
        ///CRYSTAL_GUARDIAN_SUB : Edge
        ///PAINTMASTER_MAIN : presentation
        ///CHARM_SLUG_SUPER : Dear lover
        ///NOEYES_TEMPLE_MAIN : Passport
        ///BANKER2_SUB : Thief
        ///GH_ [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CHARM_DESC_39 : Verify the musicians leaving the family of Halounast family. Business removal from the ISU newsletter is love and security is just a matter of security.
        ///INV_DESC_WALLJUMP : Harper&apos;s body was molded in the bones. Skip the user by closing the block.
        ///PIN_NAME_DREAMPLANT : good stock;
        ///CTRL_SHOW_PINS_KEY : Pinch / Key Display
        ///FLAME_COLLECTED : Crashed
        ///INV_NAME_WALLJUMP : Constraints to war
        ///PANE_MAP : Map
        ///PIN_DESC_STAG : This information describes the Department of Consumer Affairs you are  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string UI {
            get {
                return ResourceManager.GetString("UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PRECEPT_13 : Seventh: &quot;Do not be afraid&quot; &lt;Page&gt; You just have to be scared. Your faith can be a great effort. So just paint the place
        ///PRECEPT_14 : Fourth adviser: &quot;Your boss&apos;s Honor&quot; &lt;p&gt; If someone is more powerful or thoughtful, or second, you need to love them. I did not look or laugh.
        ///PRECEPT_15 : Fifteen Commandments: One enemy and destruction. &lt;Home&gt; You only need one side of the enemy. More waste. I also know how Ghadazz is, including the famine that fights against the enemy.
        ///PRECEPT_16 : 16: Avoid [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Zote {
            get {
                return ResourceManager.GetString("Zote", resourceCulture);
            }
        }
    }
}
